### PR TITLE
Enable Kotlin Explicit API Mode (Warning)

### LINKED ISSUE #279: Introduce Kotlin Explicit API mode to core-xxx modules
**Idea Description**

Explicit visibility using `public` or `internal` or `private` allows you to control what expose outside the module. Kotlin default visibility is `public`, so you may expose things you don't want to be public. 

You can force explicit visibility using [Kotlin Explicit API mode](https://github.com/Kotlin/KEEP/blob/master/proposals/explicit-api-mode.md). It helps control visibility.

⚠️ Applying Explicit API mode requires changing many parts of existing code.

### PR DESCRIPTION
**Pull request by d1-morimoto**
## Issue
- close #279

## Overview (Required)
- Kotlin Explicit API Mode warnings will display when editing core-xxx modules.

## Links
- [Kotlin Explicit API mode](https://github.com/Kotlin/KEEP/blob/master/proposals/explicit-api-mode.md)

## Screenshot
Before | After
:--: | :--:
before | after

### CODE REVIEW

**Comment by d1-morimoto** [comment]
I made this for now.
I am concerned that the following modules do not display warnings, but I can't think of a reason why.

* core-testing
* core-ui

I would appreciate it if you could give me some suggestions for modifications through your review:bow:

**Comment by takahirom** [comment]
Probably because they are android module, right?

**Comment by d1-morimoto** [comment]
Oh, that's it!
Thanks for the advice, I realized my mistake:bow:

**Comment by d1-morimoto** [comment]
I believe it has been corrected.
I would be happy to hear if there is anything else that needs to be done:bow:

* core-data
    core-data
* core-designsystem
    core-designsystem
* core-model
   core-module 
* core-testing
    core-testing
* core-ui
    core-ui
* core-zipline
    core-zipline

**Review by takahirom — APPROVED** [review]
Thanks! LGTM 👍

**Comment by d1-morimoto** [comment]
@takahirom 
Thanks for the review!

**Pull request merged**
