### PR TITLE
Activate ComposableParamOrder twitter/compose-rules and fix 

### LINKED ISSUE #518: Activate ComposableParamOrder twitter/compose-rules and fix `./gradlew composeLint`
**Idea Description**
You can activate it in https://github.com/DroidKaigi/conference-app-2022/blob/main/detekt.yml
And please fix `./gradlew composeLint`.

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2022/blob/main/detekt.yml
https://twitter.github.io/compose-rules/rules/

### PR DESCRIPTION
**Pull request by shcahill**
## Issue
- close #518 

## Overview (Required)
- activate ComposableParamOrder rule of detekt.
- order rule is below.

1. params without defaults
2. modifiers
3. params with defaults
4. optional: function that might have no default

## Links
- https://github.com/twitter/compose-rules/blob/main/rules/common/src/main/kotlin/com/twitter/compose/rules/ComposeParameterOrder.kt#L17

### CODE REVIEW

**Comment by takahirom** [comment]
Can you pull and check again?

**Comment by takahirom** [comment]
I'm rooting for you! (応援してます!)

**Comment by shcahill** [comment]
Thank you for updating this branch!
I fixed detekt issues for merged files.

**Review by takahirom — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
