### PR TITLE
Create information screen

### LINKED ISSUE #174: create  notification screen without design
**Idea Description**
create  notification screen without design

issue devided apply design

**Reference images and links**
coming soon

### PR DESCRIPTION
**Pull request by sadashi-ota**
## Issue
- close #174

## Overview (Required)
- Add `feture-announcement` module

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
I didn't see the issue 🙇 
How about naming it "announcement"?

**Comment by sadashi-ota** [comment]
Thanks for the advice!
I'll rename.

**Comment by sadashi-ota** [comment]
Renamed to 'announcement'.
Please check.

**Pull request merged**
