### PR TITLE
Implement to fetch data of sponsors

### LINKED ISSUE #178: create  sponsors list screen without design
**Idea Description**
create  sponsors list screen without design

issue devided apply design

**Reference images and links**
coming soon

### PR DESCRIPTION
**Pull request by ho2ri2s**
## Issue
- close #178

## Overview (Required)
- Fetch data from DataSource.
- Add ViewModel, Repository to flow data to UI.
- Not Implement UI.

### CODE REVIEW

**Comment by ho2ri2s** [comment]
Sorry for late 🙇 
I'll apply design with Compose, is the design completed? -> #179 
Or should I draft and implement a design? 👀

**Comment by takahirom** [comment]
Now, the design is added!

**Comment by ho2ri2s** [comment]
Thanks for the quick response to add the design 🙏

**Review by takahirom — APPROVED** [review]
Looks great 👍 
Would you fix the conflict?

**Pull request merged**
