### PR TITLE
[Docs] Correct web links

### PR DESCRIPTION
**Pull request by tshion**
Thank you for developing this repository:bow:

## Issue
- N/A

Just a few modifications, so skipped; sorry.

## Overview (Required)
This PR makes you available to visit 'cashapp' links.

## Links
- https://github.com/cashapp/molecule
- https://github.com/cashapp/zipline

## Screenshot
N/A

### CODE REVIEW

**Comment by tomoya0x00** [comment]
👀

**Comment by takahirom** [comment]
👀

**Review by takahirom — APPROVED** [review]
Thank you for reading the README🦉

**Comment by tshion** [comment]
@takahirom 
Thank you for merging:bow:

@tomoya0x00 
Thank you for making #195:bow:
(Sorry, I fail to notice......)

**Pull request merged**
