### PR TITLE
Apply slot API pattern to KaigiTag

### LINKED ISSUE #114: Make KaigiTag slot API pattern 🎰
**Describe the idea**
Currently, we are passing parameters expressly like `text: String` . But if we can use label: @[Composable](https://developer.android.com/reference/kotlin/androidx/compose/runtime/Composable) () -> [Unit](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-unit/index.html), we can also add image in it. I think it will be more flexible.

And in the KaigiTag composable, I think we can add CompositionLocalProvider to adapt the text design. 🎨 

```kotlin
    CompositionLocalProvider(
        LocalContentColor provides labelColor,
        LocalTextStyle provides labelTextStyle
    ) {
      label()
```

**Reference images and links**

* What is Slot API pattern?
You can learn Slot API Pattern here.
https://chris.banes.dev/slotting-in-with-compose-ui/

* What is KaigiTag?

image

https://github.com/DroidKaigi/conference-app-2022/blob/789e2f715776a2e30bef68442c52a2a13018ce36/core-designsystem/src/androidMain/kotlin/io/github/droidkaigi/confsched2022/designsystem/components/KaigiTag.kt#L21

* You can also use Material3 chip as a reference.

https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary#AssistChip(kotlin.Function0,kotlin.Function0,androidx.compose.ui.Modifier,kotlin.Boolean,kotlin.Function0,kotlin.Function0,androidx.compose.ui.graphics.Shape,androidx.compose.material3.ChipColors,androidx.compose.material3.ChipElevation,androidx.compose.material3.ChipBorder,androidx.compose.foundation.interaction.MutableInteractionSource)

### PR DESCRIPTION
**Pull request by r4wxii**
## Issue
- close #114

## Overview (Required)
- Apply slot API pattern to KaigiTag
- Add CompositionLocalProvider to adapt the text in label

### CODE REVIEW

**Review by takahirom — APPROVED** [review]
Looks great! 
Thank you for suggesting the Row scope.

**Comment by takahirom** [comment]
Sorry, can you resolve the conflict? 🙏

**Comment by r4wxii** [comment]
I resolved conflict 🙏

**Comment by takahirom** [comment]
Please run `./gradlew spotlessKotlinApply` 🙏

**Review by takahirom — APPROVED** [review]
🏷️

**Pull request merged**
