### PR TITLE
Add padding to session detail

### LINKED ISSUE #495: Add padding to session detail
**Idea Description**
Please add padding 16dp here.

**Reference images and links**
image

### PR DESCRIPTION
**Pull request by misuzz**
## Issue
- close #495 

## Overview (Required)
- added spacer making 16dp-padding to the bottom of the session details screen.

## Links
- 

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
Please run `./gradlew spotlessKotlinApply` 🙏

**Comment by misuzz** [comment]
I run the command you said (./gradlew spotlessKotlinApply) on the branch with my terminal, and it shows "build successful" as you can see the following.
スクリーンショット 2022-09-17 7 19 31

I thought I would push some changes after the command to solve the problem but nothing appeared.
Could you tell me what to do next?

**Comment by misuzz** [comment]
Thanks, I managed it.

**Comment by takahirom** [comment]
Thanks!

**Pull request merged**
