### PR TITLE
Translation improved.

### PR DESCRIPTION
**Pull request by Hamachi-geek**
## Issue
- close #ISSUE_NUMBER

## Overview (Required)
-Chinese and English are improved.

### CODE REVIEW

**Comment by takahirom** [comment]
There is an issue about this and it is assigned to other person. We would like to be kind to beginner software engineers. So let me close this issue. I'm looking forward to your next contribution 🙇 
https://github.com/DroidKaigi/conference-app-2022/issues/348

**Comment by takahirom** [comment]
I think you can make a pr about Chinese translation! 🙏

**Comment by Hamachi-geek** [comment]
Can I make Chinese translation?

**Comment by takahirom** [comment]
I think it is OK 👍

**Pull request closed without merging**
