### PR TITLE
add minifyEnabled for release

### LINKED ISSUE #138: Enable Proguard and see if it can run.
**Idea Description**
The title says everything.

Please add minifyEnabled = true for release and see if developRelease can run. The goal is that you launch the app. 🚀 
https://github.com/DroidKaigi/conference-app-2022/blob/main/app-android/build.gradle.kts

**Reference images and links**

### PR DESCRIPTION
**Pull request by Nthily**
## Issue
- close #138 

## Overview (Required)
- Based on the size of the generated apk, it appears that proguard and minify are enabled 🤔
- image

## Screenshot
Before | After
 |

### CODE REVIEW

**Comment by takahirom** [comment]
Can you launch the app?

**Comment by Nthily** [comment]
yes, but I can't seem to load the timetable

**Comment by takahirom** [comment]
Thanks! Can you make an issue that adds proguard rule?

**Comment by takahirom** [comment]
Sorry let me think it over 🙇

**Comment by takahirom** [comment]
I think like this.
`We can release with proguard > We can release without proguard > We can't release`
So, If you can add proguard rules. I can merge this.
I should apologize that I created a vague issue. If you would like to do that. Please do it 🙏

**Comment by takahirom** [comment]
@Nthily 
Would you like to implement this PR? If not, let me close and can I create a new issue for it? 🙇

**Comment by Nthily** [comment]
@takahirom OK, I found that even if I don't add proguard rules and minifyEnabled, it still can't show the sessions list, but I haven't tested the latest code, so let's close this PR first.

**Pull request closed without merging**
