### PR TITLE
Moved CircularProgressIndicator to center

### LINKED ISSUE #234: Add circular progress indicator Preview in session screen and move it to center
**Idea Description**
If we pass the loading, we can make the Preview. and we can set it center.

**Reference images and links**
image

https://github.com/DroidKaigi/conference-app-2022/blob/a03690dcc290e26ffe7e00c9de4f2675a126ae3d/feature-sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/Sessions.kt#L114

### PR DESCRIPTION
**Pull request by ikemura23**
## Issue
- close #234 

## Overview (Required)
- Add Box

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
Can you add a preview function to confirm it?

**Comment by takahirom** [comment]
The implementation is great 👍 Please take a look at the preview function 🙏

**Comment by ikemura23** [comment]
@takahirom 
tuika simasita d009053

image

**Review by takahirom — APPROVED** [review]
LGTM 💯

**Pull request merged**
