### PR TITLE
Make the DroidKaigi app splash screen cool 

### PR DESCRIPTION
**Pull request by masah517**
## Issue
- close #https://github.com/DroidKaigi/conference-app-2022/issues/135

## Overview (Required)
- Add Splash Screen API for backward version support lower than API 31
- Implementation of [Animated splash screen](https://developer.android.com/reference/kotlin/androidx/core/splashscreen/SplashScreen?hl=ja#themes:~:text=12%20Splash%20Screen.-,windowSplashScreenAnimatedIcon,-%3A%20The%20splash%20screen) for API level >= 31 
- Add branding image of splash screen by using [windowSplashScreenBrandingImage](https://developer.android.com/reference/android/R.attr#windowSplashScreenBrandingImage) for device version >= 31 
- Different types of splash screen according to daylight mode and night mode of the device

⚠ Please be noted that if installed from Android Studio directly the app need to be relaunched to view the splash screen

## Links
- https://developer.android.com/develop/ui/views/launch/splash-screen
- https://developer.android.com/develop/ui/views/launch/splash-screen/migrate

## Screenshot
| Daylight Mode Before  | Daylight Mode After |
| ------------- | ------------- |
|   |   |

| Night Mode Before  | Night Mode After |
| ------------- | ------------- |
|  |  |

### CODE REVIEW

**Comment by takahirom** [comment]
Thanks! Can you put the movie?

**Comment by takahirom** [comment]
How cool!!

**Comment by takahirom** [comment]
This is amazing PR!

I thought you were missing a bit of an opportunity, as your commit history may not be kept as your commit does not have an email address attached to it.
If you want to add yourself to the contributor's screen. You can add your email address that is registered to GitHub to the commit. 📫
git config --global user.email `your_gthub_registered_email_address@email.com `
https://github.com/DroidKaigi/conference-app-2022/graphs/contributors

**Comment by masah517** [comment]
Hi @takahirom -san, 
Appreciate for your prompt review. Will fix the commit's email issue asap! Thanks for the reminder 🙂

**Comment by masah517** [comment]
Hi @takahirom -san. 
I've revised the author for past commits, so please take a look at your convenience!
Thank you!

**Review by takahirom — APPROVED** [review]
Thanks for improving our first impression of our app!

**Pull request merged**
