### PR TITLE
[WIP] Separate CI workflow to post preview test comment

### LINKED ISSUE #497: Separate CI workflow to post preview test comment
**Idea Description**
Now, if you don't fork repository and create a pull request, you can see the diff of a screenshot.
https://github.com/DroidKaigi/conference-app-2022/pull/471#issuecomment-1247638122
image
But we are using `pull_request` hook that uses the forked repository's TOKEN. So you can't post a comment to the pull request.
We should separate workflow to post a comment.
I think if we download the artifact and move comment to a new workflow, we can fix it.
https://github.com/DroidKaigi/conference-app-2022/blob/main/.github/workflows/ScreenShotTest.yml#L48-L55

There is a similar sample in the GitHub blog. Please see `CommentPR.yml`.
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Reference images and links**
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

### PR DESCRIPTION
**Pull request by kwmt**
## Issue
- close #497

## Overview (Required)
- https://github.com/DroidKaigi/conference-app-2022/pull/534

## Links
- 

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
We probably need this pr for https://github.com/DroidKaigi/conference-app-2022/pull/616 . 👀

**Comment by takahirom** [comment]
@kwmt If you work on this issue, we can see the compose preview in PR! Please try it 🙏 
https://github.com/DroidKaigi/conference-app-2022/pull/640#issuecomment-1253271354

**Comment by takahirom** [comment]
@kwmt Do you have time to develop this PR? I am wondering if I should take over this task.

**Comment by kwmt** [comment]
@takahirom No, I don't.
I can't make any time to develop, so you can unassign me.

**Comment by takahirom** [comment]
OK! Thanks for developing and telling me!

**Comment by takahirom** [comment]
I'll take over this branch and commit
Let me close once this PR.

**Pull request closed without merging**
