### PR TITLE
[test] fix action CommentPR

### PR DESCRIPTION
**Pull request by nashcft**
test for #734

### CODE REVIEW

**Comment by takahirom** [comment]
Probably you should add some changes for running the comment action.

**Comment by takahirom** [comment]
Like this
https://github.com/DroidKaigi/conference-app-2022/pull/724/files

**Comment by nashcft** [comment]
Thanks for the information 🙏

**Comment by takahirom** [comment]
Sorry. Probably you need to merge for testing.

**Comment by nashcft** [comment]
ah, sorry. I just doubted my understanding and confirmed what the comment job did.

**Comment by nashcft** [comment]
so we'll revert this test PR after merge and test with the change, right?

**Comment by takahirom** [comment]
@nashcft
We have to merge the workflow changes. But we don't need to merge design change to main.
The changes in pr are used and the workflow is used in main.
So you can open two PRs that change workflow to merge and change the design to test.

**Comment by nashcft** [comment]
@takahirom 

Let me confirm my understanding of what to do 🙏 

First, we need to open following two PRs:

1. includes only the change to the workflow yml file `CommentPR.yml` to fix #734
2. includes some changes to UI layout to test if the fix above works as expected

Then what we'll do for the test are...

1. open and merge PR 1 to apply the fix into `main` branch
2. open PR 2 to test the merged change
3. if the result of test is...
  - successful: the issue has been solved 🎉 
  - failure: ok let's try another fix

please tell me if something in my understanding wrong 🙏

**Comment by takahirom** [comment]
That's exactly what I mean!

**Comment by nashcft** [comment]
Thank you! Then I'd like to rework this as new PRs along https://github.com/DroidKaigi/conference-app-2022/pull/738#issuecomment-1257157393

**Pull request closed without merging**
