### PR TITLE
Move KaigiScaffold and KaigiTopAppBar to proper package

### PR DESCRIPTION
**Pull request by Seo-4d696b75**
## Issue
- close https://github.com/DroidKaigi/conference-app-2022/issues/310

## Overview (Required)
- move the following 2 compose functions in `io.github.droidkaigi.confsched2022.designsystem.theme` package to `io.github.droidkaigi.confsched2022.designsystem.components`
  - `KaigiScaffold`
  - `KaigiTopAppBar`

**Note**   
Compose Preview function of `KaigiScaffold` has also moved.

## Screenshot

Omitted because no effects to appearance of any UI.

### CODE REVIEW

**Comment by takahirom** [comment]
Please resolve conflict 🙏

**Comment by takahirom** [comment]
Let me see this tomorrow. 👀

**Review by takahirom — APPROVED** [review]
Thank you for your cooporation! Please resolve the conflict 🙏

**Comment by Seo-4d696b75** [comment]
@takahirom Thank you for your approval. The conflicts have been resolved!

**Comment by takahirom** [comment]
Can you run ./gradlew spotlessKotlinApply?🙏

**Comment by takahirom** [comment]
> Sponsors.kt: (11, 62): Unresolved reference: KaigiScaffold

Can you fix import? 🙏

**Comment by Seo-4d696b75** [comment]
> Sponsors.kt: (11, 62): Unresolved reference: KaigiScaffold

I'm confused because there is no file named `Sponsors.kt`.   
Running lint by GithubActions failed, but running it in my local project works without any error.

Is this related to gradle cache or something? @takahirom

**Comment by takahirom** [comment]
Can you update your project?

**Comment by Seo-4d696b75** [comment]
It seems I missed to fetch some commits from main branch. Thank you for your advice 🙇 
@takahirom

**Comment by takahirom** [comment]
Thanks for fighting with conflict 💥

**Pull request merged**
