### PR TITLE
Fix ExplicitApi in core-data

### LINKED ISSUE #536: Fix ExplicitApi in core-data
**Idea Description**
Please add `public` if it is used in other classes, if not, please add private for all classes, property, and functions.
image

**Reference images and links**
https://kotlinlang.org/docs/whatsnew14.html#explicit-api-mode-for-library-authors

### PR DESCRIPTION
**Pull request by kumokumot**
## Issue
- close #536

## Overview (Required)
- Xplicitly specify access modifiers public or private  in core-data. 
(In the local environment, I checked in strict mode)

## Links
- https://kotlinlang.org/docs/whatsnew14.html#explicit-api-mode-for-library-authors

### CODE REVIEW

**Comment by takahirom** [comment]
Thanks! Can you set explicitApiError() to the build.gradle?
https://github.com/DroidKaigi/conference-app-2022/blob/main/core-data/build.gradle.kts#L14

**Comment by kumokumot** [comment]
@takahirom 
> Thanks! Can you set explicitApiError() to the build.gradle?

[98c6be8](https://github.com/DroidKaigi/conference-app-2022/pull/554/commits/98c6be86e4ec91c901beca92cc264858c62d001c)  
I changed the mode from Warning to Error.

**Comment by takahirom** [comment]
Thanks for your cooperation!
Would you check the iosMain sources?
e: /Users/runner/work/conference-app-2022/conference-app-2022/core-data/src/iosMain/kotlin/io/github/droidkaigi/confsched2022/KoinModules.kt: (27, 1): Visibility must be specified in explicit API mode

e: /Users/runner/work/conference-app-2022/conference-app-2022/core-data/src/iosMain/kotlin/io/github/droidkaigi/confsched2022/KoinModules.kt: (27, 5): Return type must be specified in explicit API mode
> Task :core-data:compileKotlinIosX64 FAILED
e: /Users/runner/work/conference-app-2022/conference-app-2022/core-data/src/iosMain/kotlin/io/github/droidkaigi/confsched2022/data/NativeDriverFactory.kt: (6, 1): Visibility must be specified in explicit API mode

**Comment by kumokumot** [comment]
I had missed it. I fixed iosMain.

**Comment by takahirom** [comment]
Thanks for your contribution!

**Pull request merged**
